### ISSUE TITLE
Support for the newly released Reppo AEM-7

### ISSUE THREAD

**Issue by Slenderman7676** [YoRyan/open-nec#13]
A new AEM-7 model has arrived. I don't own it yet but it looks nice from screenshots. Just needs OpenNEC support and it will be better.

**Comment by YoRyan** [comment]
I have not purchased the DLC yet, either. If we have a complete enough ADU (from the screenshots, it looks like it has space for ACSES), I might attempt a full Open NEC engine script replacement; otherwise, I’ll just contribute some wrapper code to the community enhancement pack, as I did for the E-60.

**Comment by YoRyan** [comment]
So I've purchased it. It does come with an independent ACSES display (wired out of the box as a simple track speed indicator, like the OG AEM-7), so it's a good candidate for Open NEC.

The problem is, it also includes a bunch of Reppo scripting magic that I'm really not inclined to recreate with a clean-room implementation. So we would have to somehow preserve the original script, which means the .out file has to be extracted from the asset pack, which means we would have to introduce an installation script or program.

**Comment by YoRyan** [comment]
With 8c0a510785a870c54a3f1ac863204d81708a70ff and 2d9a2dcca4b27aae7631de7a48d58e9180b3068d we now have support for the AEM-7 and the E60, featuring Open NEC's safety systems and support for the enhanced Amfleet's brake lights and trapdoor toggle.
