### ISSUE TITLE
Throttle/Dynamic Brake Issue With ALP45-DP

### ISSUE THREAD

**Issue by PupWithHat** [YoRyan/open-nec#14]
Hello, first time commenting/posting. I noticed whenever the ALP-45DP is in diesel powered mode the throttle only powers to 61% and the RPMS are limited to around 1300. this only happens when the train starts in diesel mode and this applies to the Comet IV,V and Multilevel Cab Car when the ALP-45DP is the locomotive on the consist. When the Locomotive is in electric overhead mode this does not happen but the locomotive seems to be consuming fuel. Starting the locomotive in electric overhead mode and then changing over to diesel mode causes the throttle issue and limits the RPMS. id be happy to provide screen captures  if needed.

**Comment by YoRyan** [comment]
Hi, thanks for commenting, and so sorry for the long delay.

The power limiting in diesel mode is actually intentional, to simulate the ALP45's lower power output when using the diesel engine. According to [Wikipedia](https://en.wikipedia.org/wiki/Bombardier_ALP-45DP), the locomotive's max power to rail is 3600 hp in diesel mode and 5900 hp in electric. So in electric mode we just multiply the throttle output by (3600 / 5900) to reduce the maximum power. As you've noticed, the vanilla script doesn't do this, but I thought it would be a fun realism feature to include. I'm open to reverting it.

As for the fuel consumption in electric mode, this happens with the vanilla script as well. There are no dual-mode locomotives in Train Simulator, just diesel locomotives with some script trickery to force the throttle to 0 if not using the correct power mode. There is no way for an engine script to instruct the simulator to "suspend" the consumption of fuel, either.
