### ISSUE TITLE
Issue with NJT ADU on Comet V & Multilevel

### ISSUE THREAD

**Issue by TovPrap** [YoRyan/open-nec#2]
I have noticed on the NJT style ADU in the cab cars of the Comet V and Multilevel, the green arc does not show the track speed limit, but functions as the speed needle of a gauge. The alarms turn on and whatnot, but you don't exactly know what speed limit you have with the current set up of the ADU.

**Comment by YoRyan** [comment]
Hey, first GitHub issue! Thanks so much for the report.

Unfortunately, the green speed bar is not always under the control of Lua. Sometimes, DTG hardcoded the bar to act as a speedometer, irregardless of whatever control values the engine script sets. This is true for the models you've mentioned and also, I believe, the Arrow III.

It's likely possible to fix this by modifying the engine blueprints, but I'm always hesitant to make such a change, because other mods (Fan Railer, enhancement packs, etc.) often modify those kinds of files. So I've decided we can just live with this quirk on certain trains—but it would certainly not be a bad idea to make a note of it in the documentation.

**Comment by TovPrap** [comment]
This is a great project, and I love giving feedback, to help improve it!

I recall the Arrow III functions as intended.

It would be good to add in the notes section for these cab cars, that they have this issue with the ADU. At first I thought I had not installed it correctly.

**Comment by YoRyan** [comment]
Fixing for v2 by using the red speed bar to show the target speed—just for the ALP-45 version of the cab car, which is the only one this bug affects. Cheers!
