### ISSUE TITLE
signal speed stuck at 20 mph

### ISSUE THREAD

**Issue by donnie67** [YoRyan/open-nec#5]
Hi

I observed an issue with Amtrak Acela on the Typical Day scenari0

The signals are all green but the ATC readout says 20 MPH for the route.   The track speed is correct and enforced but the signal speed doesnt seem right and is not even enforced at 20 mph..

thank you

**Comment by YoRyan** [comment]
Yeah, I noticed this too. My control state dialog shows that Open NEC is setting the right signal speed, but something in the simulator is keeping the Acela's "20" digits visible. I was never able to figure out what it was. It only seems to happen during Washington-Baltimore scenarios, too.

Thanks for the reminder. It's worth a note in the documentation.

**Comment by donnie67** [comment]
Ryan 
tx for the reply.
Are you still doing mods on TS?


-----Original Message-----

**Comment by YoRyan** [comment]
Indeed I am—I've been slowly working on a v2 rewrite of OpenNEC over the past year. The new version will use TypeScript instead of Lua, so it should be significantly more stable. It will also come with some neat features like fading headlights (for some locomotives).

I'm also involved with that work-in-progress Amfleet enhancement pack for the E60 DLC. My job is to script the low-floor/high-floor modes and the brake indicator lights.

**Comment by YoRyan** [comment]
Between the recent core updates and the TypeScript port, it looks like this bug is no longer present. Huzzah!

**Comment by donnie67** [comment]
Very nice!  Tx for the update!
